//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKisibilgigoster")]
    public interface IKisibilgigoster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKisibilgigoster/Kisibilgigoster", ReplyAction="http://tempuri.org/IKisibilgigoster/KisibilgigosterResponse")]
        System.Data.DataSet Kisibilgigoster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKisibilgigoster/Kisibilgigoster", ReplyAction="http://tempuri.org/IKisibilgigoster/KisibilgigosterResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> KisibilgigosterAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKisibilgigosterChannel : WebApplication1.ServiceReference1.IKisibilgigoster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KisibilgigosterClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IKisibilgigoster>, WebApplication1.ServiceReference1.IKisibilgigoster {
        
        public KisibilgigosterClient() {
        }
        
        public KisibilgigosterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KisibilgigosterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisibilgigosterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisibilgigosterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Kisibilgigoster() {
            return base.Channel.Kisibilgigoster();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> KisibilgigosterAsync() {
            return base.Channel.KisibilgigosterAsync();
        }

        internal object Kisibilgigoster(string tckno)
        {
            throw new NotImplementedException();
        }
    }
}
